version: 2.1

orbs:
  cimg: circleci/cimg@0.6.2
  slack: circleci/slack@4.12.1

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          update-script: deployFeed.sh
          context:
            - cpe-image-bot-github-creds
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          resource-class: 2xlarge+
          docker-namespace: ccitest
          docker-repository: deploy
          filters:
            branches:
              ignore:
                - main
          context: cimg-docker-image-building
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - cimg/build-and-deploy:
          name: "Deploy"
          resource-class: 2xlarge+
          docker-repository: deploy
          filters:
            branches:
              only:
                - main
          context:
            - cimg-docker-image-building
            - cimg-docker-image-publishing
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - trigger-images:
          matrix:
            parameters:
              deploy-images:
                - cimg-aws
                - cimg-azure
                - cimg-gcp
          context: cpe-image-bot-github-creds
          requires:
            - Deploy
          filters:
            branches:
              only:
                - main

jobs:
  trigger-images:
    parameters:
      deploy-images:
        type: string
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Check if release build"
          command: |
            if ! git log -1 --pretty=%s | grep "\[release\]"; then
              echo "Not a release commit"
              circleci step halt
            fi
      - run:
          name: "Trigger utility image builds"
          command: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/CircleCI-Public/<<parameters.deploy-images>>/pipeline \
            --header "Circle-Token: $IMAGE_BOT_TOKEN" \
            --header "content-type: application/json" \
            --data '{"parameters":{"trigger": true}, "branch": "main" }}'
